### ISSUE TITLE
android 8.0上通知发不出去

### ISSUE THREAD

**Issue by protectedMan** [lovejjfg/EasyJump#1]
![image](https://user-images.githubusercontent.com/17565737/50371971-4a6dfe80-0600-11e9-8612-f6b2993c456e.png)
貌似没有适配8.0的通知

**Comment by lovejjfg** [comment]
多谢指出，一直忘记更新了。https://github.com/lovejjfg/EasyJump/commit/ea2f7c0aabb9075b83f9cbf99b66004a932c6809#diff-4a27d9d27a37295850576d2822abb474 最新代码阔以使用了。
